name: Android CI (primary)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create google-services.json
        env:
          google_services_json: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $google_services_json | base64 -d > voipms-sms/src/primary/google-services.json
      - name: Build with Gradle
        run: ./gradlew assemblePrimaryFullRelease