name: Android CI (F-Droid)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Prepare source for F-Droid build
        run: sed -i "/fdroid-remove-start/,/fdroid-remove-end/d" build.gradle voipms-sms/build.gradle
      - name: Build with Gradle (F-Droid)
        run: ./gradlew assembleFdroidFullRelease